// This file is auto-generated by ./bin/rails stimulus:install
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ResponsiveTabsController from "./responsive_tabs_controller"
application.register("responsive-tabs", ResponsiveTabsController)