name: Deploy PR to Staging

on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number to deploy (optional, will use current branch if not specified)'
        required: false
        type: string

jobs:
  deploy:
    name: Deploy PR to staging
    runs-on: ubuntu-latest
    environment: staging
    concurrency: deploy-staging-group    # ensure only one staging deployment runs at a time
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to staging
        run: flyctl deploy --config fly.staging.toml --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Comment PR with staging URL
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🚀 Staging deployment complete!\n\n**Staging URL:** https://travelapp-staging.fly.dev'
            })
